/**
 * Vercel Deployment Service
 * Handles deploying generated code to Vercel
 */

export interface DeployConfig {
  projectName: string
  framework: 'nextjs' | 'react' | 'static'
  files: DeployFile[]
  environmentVariables?: Record<string, string>
}

export interface DeployFile {
  path: string
  content: string
}

export interface DeployResult {
  success: boolean
  url?: string
  projectId?: string
  deploymentId?: string
  error?: string
}

/**
 * Build a complete Next.js project from generated animation code
 */
export function buildProjectFiles(code: string, componentName: string): DeployFile[] {
  const files: DeployFile[] = []

  // package.json
  files.push({
    path: 'package.json',
    content: JSON.stringify({
      name: componentName.toLowerCase().replace(/[^a-z0-9]/g, '-'),
      version: '1.0.0',
      private: true,
      scripts: {
        dev: 'next dev',
        build: 'next build',
        start: 'next start',
      },
      dependencies: {
        next: '^15.0.0',
        react: '^19.0.0',
        'react-dom': '^19.0.0',
        'framer-motion': '^11.0.0',
        'lucide-react': '^0.400.0',
      },
      devDependencies: {
        '@types/node': '^22.0.0',
        '@types/react': '^19.0.0',
        typescript: '^5.0.0',
        tailwindcss: '^3.4.0',
        autoprefixer: '^10.4.0',
        postcss: '^8.4.0',
      },
    }, null, 2),
  })

  // tsconfig.json
  files.push({
    path: 'tsconfig.json',
    content: JSON.stringify({
      compilerOptions: {
        target: 'es5',
        lib: ['dom', 'dom.iterable', 'esnext'],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: 'esnext',
        moduleResolution: 'bundler',
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: 'preserve',
        incremental: true,
        plugins: [{ name: 'next' }],
        paths: { '@/*': ['./src/*'] },
      },
      include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
      exclude: ['node_modules'],
    }, null, 2),
  })

  // next.config.js
  files.push({
    path: 'next.config.js',
    content: `/** @type {import('next').NextConfig} */
const nextConfig = {}
module.exports = nextConfig
`,
  })

  // tailwind.config.js
  files.push({
    path: 'tailwind.config.js',
    content: `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
`,
  })

  // postcss.config.js
  files.push({
    path: 'postcss.config.js',
    content: `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
`,
  })

  // src/app/layout.tsx
  files.push({
    path: 'src/app/layout.tsx',
    content: `import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: '${componentName}',
  description: 'Generated by WebMotion.ai',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
`,
  })

  // src/app/globals.css
  files.push({
    path: 'src/app/globals.css',
    content: `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --foreground-rgb: 0, 0, 0;
  --background-start-rgb: 214, 219, 220;
  --background-end-rgb: 255, 255, 255;
}

@media (prefers-color-scheme: dark) {
  :root {
    --foreground-rgb: 255, 255, 255;
    --background-start-rgb: 0, 0, 0;
    --background-end-rgb: 0, 0, 0;
  }
}

body {
  color: rgb(var(--foreground-rgb));
  background: linear-gradient(
      to bottom,
      transparent,
      rgb(var(--background-end-rgb))
    )
    rgb(var(--background-start-rgb));
}
`,
  })

  // src/app/page.tsx - the generated component
  files.push({
    path: 'src/app/page.tsx',
    content: code,
  })

  return files
}

/**
 * Generate a deploy-ready project as a downloadable ZIP
 */
export async function downloadProject(files: DeployFile[]): Promise<void> {
  // For client-side, we'll create a simple concatenation
  // In production, you'd use a ZIP library like JSZip
  const readme = `# Generated by WebMotion.ai

## Files
${files.map(f => `- ${f.path}`).join('\n')}

## Setup
1. Install dependencies: \`npm install\`
2. Run development server: \`npm run dev\`
3. Build for production: \`npm run build\`

## Deploy to Vercel
1. Push to GitHub
2. Import project on vercel.com
3. Deploy automatically
`

  const allContent = files.map(f => 
    `=== ${f.path} ===\n${f.content}\n`
  ).join('\n')

  // Create downloadable file
  const blob = new Blob([
    readme + '\n\n' + allContent
  ], { type: 'text/plain' })
  
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = 'webmotion-project.txt'
  a.click()
  URL.revokeObjectURL(url)
}

/**
 * Deploy to Vercel via API (requires Vercel token)
 */
export async function deployToVercel(
  config: DeployConfig,
  token?: string
): Promise<DeployResult> {
  if (!token) {
    return {
      success: false,
      error: 'Vercel token not configured. Add VERCEL_TOKEN to .env.local',
    }
  }

  try {
    // Create deployment
    const response = await fetch('https://api.vercel.com/v13/deployments', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        name: config.projectName,
        files: config.files.map(f => ({
          file: f.path,
          data: Buffer.from(f.content).toString('base64'),
          encoding: 'base64',
        })),
        projectSettings: {
          framework: config.framework === 'nextjs' ? 'nextjs' : null,
          buildCommand: 'npm run build',
          outputDirectory: '.next',
        },
        target: 'production',
      }),
    })

    if (!response.ok) {
      const error = await response.text()
      return { success: false, error: `Vercel API error: ${error}` }
    }

    const data = await response.json()
    return {
      success: true,
      url: `https://${data.url}`,
      projectId: data.projectId,
      deploymentId: data.id,
    }
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Deployment failed',
    }
  }
}

/**
 * Get deployment status
 */
export async function getDeploymentStatus(
  deploymentId: string,
  token: string
): Promise<{ ready: boolean; url?: string; error?: string }> {
  try {
    const response = await fetch(
      `https://api.vercel.com/v13/deployments/${deploymentId}`,
      {
        headers: { Authorization: `Bearer ${token}` },
      }
    )

    if (!response.ok) {
      return { ready: false, error: 'Failed to fetch status' }
    }

    const data = await response.json()
    return {
      ready: data.readyState === 'READY',
      url: data.url ? `https://${data.url}` : undefined,
      error: data.readyState === 'ERROR' ? data.errorMessage : undefined,
    }
  } catch (error) {
    return { ready: false, error: 'Network error' }
  }
}
